// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoVv5eR58dgqV-jErwnREqXWU3oEOHO4',
    appId: '1:265741029614:android:3c6baf905b55f690c123ff',
    messagingSenderId: '265741029614',
    projectId: 'finzycash-2da36',
    storageBucket: 'finzycash-2da36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xosuqFsXVC3f-ai7jlE67vGfVee2Zfc',
    appId: '1:265741029614:ios:8e2e0a3d0b0ca5e8c123ff',
    messagingSenderId: '265741029614',
    projectId: 'finzycash-2da36',
    storageBucket: 'finzycash-2da36.firebasestorage.app',
    androidClientId: '265741029614-1g2ul7ea0td35eljfnbif67uc0179rqi.apps.googleusercontent.com',
    iosClientId: '265741029614-fkapp7pi0klmm4223u0qefrsf6dqqfib.apps.googleusercontent.com',
    iosBundleId: 'com.financemanagerapp.financeManagerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApeQlWJlm1BuiclETDAJ_l2qdwPvgtuIc',
    appId: '1:265741029614:web:cdb64e5c601ee0bbc123ff',
    messagingSenderId: '265741029614',
    projectId: 'finzycash-2da36',
    authDomain: 'finzycash-2da36.firebaseapp.com',
    storageBucket: 'finzycash-2da36.firebasestorage.app',
    measurementId: 'G-9SSGGKKZV7',
  );

}